export const blogData = [
  {
    Sports: {
      firstImg: "/images/sport-sub1.avif",
      firstTitle: "Get Ready for Lacrosse Season",
      firstText: "Gear up for your best season yet",
      secondImg: "/images/sport-sub2.avif",
      secondTitle: "Find Your Perfect Cleats",
      secondText: "Discover the latest styles from all of our top brands",
      thirdImg: "/images/sport-sub3.avif",
      thirdTitle: "Get Back to the Gridiron Grid",
      thirdText: "Gear up with the latest football essentials",
      fourthImg: "/images/sport-sub4.avif",
      fourthTitle: "Pickleball HQ",
      fourthText: "Gear up with everything you need to rule the court",
    },
  },
  {
    Men: {
      firstImg: "/images/men-sub1.webp",
      firstTitle: "ON Cloudnova",
      firstText: "Your All-Day Sneaker",
      secondImg: "/images/men-sub2.avif",
      secondTitle: "Gear Up For Your Next Run",
      secondText: "Hit Your Stride with Running Essentials",
      thirdImg: "/images/men-sub3.avif",
      thirdTitle: "Tees, Tanks, and Shorts",
      thirdText: "Get comfortable in tees, shorts and more",
      fourthImg: "/images/men-sub4.webp",
      fourthTitle: "New Swim, Sandals & More",
      fourthText: "Chubbies, Hurley and more",
    },
  },
  {
    Women: {
      firstImg: "/images/women-sub1.webp",
      firstTitle: "White Hot",
      firstText: "Lace up in a crisp new pair",
      secondImg: "/images/women-sub2.webp",
      secondTitle: "Summer Essentials",
      secondText: "Tees. Tanks. Shorts.",
      thirdImg: "/images/women-sub3.webp",
      thirdTitle: "Vacation Vibes",
      thirdText: "Suits and sandals for the beach",
      fourthImg: "/images/women-sub4.webp",
      fourthTitle: "High Style. High Performance.",
      fourthText: "Meet your workout must-haves",
    },
  },
  {
    Health: {
      firstImg: "/images/health-sub1.webp",
      firstTitle: "New! CALIA Fitness Equipment",
      firstText: "Yoga and training essentials designed for studio and at home",
      secondImg: "/images/health-sub2.avif",
      secondTitle: "Up To 45% Off Select Weight Training",
      secondText: "Save on Fitness Gear, ETHOS and more",
      thirdImg: "/images/health-sub3.jpg",
      thirdTitle: "Recover and Recharge",
      thirdText: "With essentials from Therabody and more",
      fourthImg: "/images/health-sub4.avif",
      fourthTitle: "Free Ship To Store",
      fourthText:
        "Save on shipping and get free ship to store on select styles",
    },
  },
  {
    Outdoor: {
      firstImg: "/images/outdoor-sub1.avif",
      firstTitle: "20% Off Igloo Coolers",
      firstText:
        "Keep your refreshments chill wherever you go & no matter the occassion",
      secondImg: "/images/outdoor-sub2.webp",
      secondTitle: "Up to 50% Off Summer Fishing Deals",
      secondText: "Reel in the savings",
      thirdImg: "/images/outdoor-sub3.avif",
      thirdTitle: "$50 Off Select Blackstone Griddles",
      thirdText: "Plus, more outdoor cooking deals",
      fourthImg: "/images/outdoor-sub4.avif",
      fourthTitle: "Beach Gear",
      fourthText: "Complete your sandy set up with these must-haves",
    },
  },
  {
    "Fan Shop": {
      firstImg: "/images/fan-sub1.avif",
      firstTitle: "Your Team. Your Town. Let ‘Em Know.",
      firstText: "Nike x MLB™ City Connect Collection",
      secondImg: "/images/fan-sub2.avif",
      secondTitle: "House of Jerseys",
      secondText: "Rock Your Favorite Player",
      thirdImg: "/images/fan-sub3.avif",
      thirdTitle: "Gear Up for Glory",
      thirdText: "USWNT Gear",
      fourthImg: "/images/fan-sub4.avif",
      fourthTitle: "Fan Shop Sale!",
      fourthText: "Score savings on your favorite team’s gear",
    },
  },
  {
    Accessories: {
      firstImg: "/images/accessories-sub1.avif",
      firstTitle: "Meet Your Wearable Health and Fitness Coach",
      firstText: "Sleep, train and recover with WHOOP 4.0",
      secondImg: "/images/accessories-sub2.avif",
      secondTitle: "Duffel Bags",
      secondText: "Get there in style with bags for every occasion",
      thirdImg: "/images/accessories-sub3.avif",
      thirdTitle: "New Summer Sunglasses",
      thirdText: "Accessorize with shades from top brands",
    },
  },
];
